# Configuración de MongoDB
spring:
  application:
    name: SistemaIAs
  data:
    mongodb:  
      uri: mongodb+srv://maylinjauregui:oTDesoVuG2nx4AdJ@cluster0.5djyl.mongodb.net/BD_IAs?appName=Cluster0

# Configuración del servidor
server:
  port: 8080

# Configuración de RapidAPI
rapidapi:
  chat:
    url: https://chatgpt-42.p.rapidapi.com/chat
    key: 3204aced1emshc2f6e2f457e41a6p179f64jsn5228ec0ef14b
    host: chatgpt-42.p.rapidapi.com
  ghibli:
    url: https://ai-ghibli-image-generator.p.rapidapi.com/texttoimageghibli
    key: 4e8255b460msh51338a6d8ba2bcep179502jsnbeebe5f14964
    host: ai-ghibli-image-generator.p.rapidapi.com

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    pe.edu.vallegrande.SistemaIAs: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
