# kubectl apply -f maylin-jauregui-22-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: maylin-jauregui-22-secret
  namespace: maylin-jauregui-22-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tYXlsaW5qYXVyZWd1aTpvVERlc29WdUcybng0QWRKQGNsdXN0ZXIwLjVkanlsLm1vbmdvZGIubmV0L0JEX0lBcz9hcHBOYW1lPUNsdXN0ZXIw   # en Base64
  GHIBLI_URL: aHR0cHM6Ly9haS1naGlibGktaW1hZ2UtZ2VuZXJhdG9yLnAucmFwaWRhcGkuY29tL3RleHR0b2ltYWdlZ2hpYmxp  # en Base64
  GHIBLI_KEY: ZjZmMjRlY2RlOW1zaGQwMjkyYjE3YTZhYmM1ZnAxMTM0NWZqc242NzgzYjczMmI4Y2Y=  # en Base64
  GHIBLI_HOST: YWktZ2hpYmxpLWltYWdlLWdlbmVyYXRvci5wLnJhcGlkYXBpLmNvbQ==   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode